CREATE TABLE accounts(
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR UNIQUE NOT NULL,
  user_id UUID UNIQUE NOT NULL,
  FOREIGN KEY("user_id") REFERENCES auth.users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
